# ------------------------------ #
#  Teleportals Spigot MC Plugin  #
#      Configuration File        #
# ------------------------------ #

# The message strings used by the game. Includes color codes
# and formatters. If you decide to edit these, make sure the
# amount and type of formatters are unchanged.
messages:
  tag: "&f&l[&bTele&3Portals&f&l]&r "
  no-perms: "&cInsufficient permissions"
  unknown-cmd: "&cUnknown command: \"%s\""
  invalid-arg: "&cInvalid argument given: \"%s\""
  config-reloaded: "&6The config was reloaded by &e%s"
