# ------------------------------ #
#  Teleportals Spigot MC Plugin  #
#      Configuration File        #
# ------------------------------ #

# The messages used by the plugin. Includes color codes
# and formatters. If you decide to edit these, make sure
# the amount and type of formatters are unchanged.
messages:
  tag: "&f&l[&bTeleportals&f&l]&r "
  no-perms: "&cInsufficient permissions"
  unknown-cmd: "&cUnknown command: \"%s\""
  invalid-arg: "&cInvalid argument given: \"%s\""
  config-reloaded: "&6The config was reloaded by &e%s"

# Customize the gateway prism item's text.
# Requires a server reload for changes to take effect.
gateway-prism:
  display: "&bGateway Prism"
  lore:
    - "&7Shift + right click to LINK."
    - "&7Right click to ACTIVATE."
