# ------------------------------ #
#  Teleportals Spigot MC Plugin  #
#      Configuration File        #
# ------------------------------ #

# The messages used by the plugin. Includes color codes
# and formatters. If you decide to edit these, make sure
# the amount and type of formatters are unchanged.
messages:
  tag: "&f&l[&bTeleportals&f&l]&r "
  no-perms-cmd: "&cInsufficient permission to perform that command."
  no-perms-craft: "&cInsufficient permission to craft that item."
  no-perms-link: "&cInsufficient permission to link with teleportals."
  no-perms-activate: "&cInsufficient permission to activate teleportals."
  no-perms-deactivate: "&cInsufficient permission to deactivate teleportals."
  no-perms-use: "&cInsufficient permission to use teleportals."
  not-player: "&cYou must be an in-game player to use that command."
  unknown-cmd: "&cUnknown command: \"%s\""
  invalid-arg: "&cInvalid argument given: \"%s\""
  spawned-item: "&aSpawned in a gateway prism."
  config-reloaded: "&6The config was reloaded by &e%s"
  plugin-info: |
    &aSending plugin information...
    &6---==-&f[&e %s Plugin &f]&6-==---
    &aVersion: &b%s
    &aAuthors: &b%s
    &aDescription: &b%s
    &aWebsite: &b%s
    &7------------------------
    &c/teleportals &7- display plugin help and information.
    &c/teleportals spawnitem &7- give yourself a gateway prism.
    &c/teleportals reloadconfig &7- reload the plugin's configuration file.

# Customize the plugin's gateway prism item.
# You may use 'recipe-shapeless' instead of 'recipe-shaped'.
# Requires a full plugin reload for changes to take effect.
# Does not affect existing items in the world.
# Existing items will still work.
gateway-prism:
  amount: 1
  material: GOLDEN_SWORD
  display: "&bGateway Prism"
  lore:
    - "&7Shift + right click to LINK."
    - "&7Right click to ACTIVATE."
  # recipe-shapeless:
  #   - ENDER_EYE
  #   - DRAGON_HEAD
  #   - ENDER_EYE
  #   - SHULKER_SHELL
  #   - END_CRYSTAL
  #   - SHULKER_SHELL
  #   - GOLD_INGOT
  #   - BEACON
  #   - GOLD_INGOT
  recipe-shaped:
    shape:
      - "OwO"
      - "*u*"
      - "-v-"
    map:
      'O': ENDER_EYE
      '*': SHULKER_SHELL
      '-': GOLD_INGOT
      'w': DRAGON_HEAD
      'u': END_CRYSTAL
      'v': BEACON
