# ------------------------------ #
#  Teleportals Spigot MC Plugin  #
#      Configuration File        #
# ------------------------------ #

# The messages used by the plugin. Includes color codes
# and formatters. If you decide to edit these, make sure
# the amount and type of formatters are unchanged.
messages:
  tag: "&f&l[&bTeleportals&f&l]&r "
  no-perms-cmd: "&cInsufficient permission to perform that command."
  no-perms-craft: "&cInsufficient permission to craft that item."
  no-perms-link: "&cInsufficient permission to link with teleportals."
  no-perms-activate: "&cInsufficient permission to activate teleportals."
  no-perms-deactivate: "&cInsufficient permission to deactivate teleportals."
  no-perms-use: "&cInsufficient permission to use teleportals."
  unknown-cmd: "&cUnknown command: \"%s\""
  invalid-arg: "&cInvalid argument given: \"%s\""
  config-reloaded: "&6The config was reloaded by &e%s"
  plugin-info: |
    &aSending plugin information...
    &6---==-&f[&e %s Plugin &f]&6-==---
    &aVersion: &b%s
    &aAuthors: &b%s
    &aDescription: &b%s
    &aWebsite: &b%s
    &7------------------------
    &c/teleportals &7- display plugin help and information.
    &c/teleportals reloadconfig &7- reload the plugin's configuration file.

# Customize the plugin's gateway prism item.
# Requires a plugin reload for changes to take effect.
# Does not change existing items in the world.
gateway-prism:
  amount: 1
  display: "&bGateway Prism"
  lore:
    - "&7Shift + right click to LINK."
    - "&7Right click to ACTIVATE."
