# ------------------------------ #
#  Teleportals Spigot MC Plugin  #
#      Configuration File        #
# ------------------------------ #

# The messages used by the plugin. Includes color codes
# and formatters. If you decide to edit these, make sure
# the amount and type of formatters are unchanged.
messages:
  tag: "&f&l[&bTeleportals&f&l]&r "
  no-perms-cmd: "&cInsufficient permission to perform that command."
  no-perms-craft: "&cInsufficient permission to craft that item."
  no-perms-link: "&cInsufficient permission to link with teleportals."
  no-perms-activate: "&cInsufficient permission to activate teleportals."
  active-portal-limit: "&cYou've reached your teleportal limit of &6%d&c."
  no-perms-deactivate: "&cInsufficient permission to deactivate teleportals."
  no-perms-use: "&cInsufficient permission to use teleportals."
  cant-cross-worlds: "&cYou cannot link a teleportal from &e%s &cto &e%s"
  not-player: "&cYou must be an in-game player to use that command."
  unknown-cmd: "&cUnknown command: \"%s\""
  invalid-arg: "&cInvalid argument given: \"%s\""
  spawned-item: "&aSpawned in a gateway prism."
  config-reloaded: "&6The config was reloaded by &e%s"
  plugin-info: |
    &aSending plugin information...
    &6---==-&f[&e %s Plugin &f]&6-==---
    &aVersion: &b%s
    &aAuthors: &b%s
    &aDescription: &b%s
    &aWebsite: &b%s
    &7------------------------
    &c/teleportals &7- display plugin help and information.
    &c/teleportals spawnitem &7- give yourself a gateway prism.
    &c/teleportals reloadconfig &7- reload the plugin's configuration file.

# Create permission groups for the plugin.
# Specific, optional limits can be applied to players who have
#   the permission node 'teleportals.group.<name>',
#   where <name> is one of the groups defined below.
#
# Here are the optional limits you can define:
#  * max-active-portals: non-negative integer
#  * worlds-can-activate: list of strings (a world whitelist)
#  * worlds-cannot-activate: list of strings (alternatively, a world blacklist)
#
# Here is an example:
# # groups:
# #   normalplayer:
# #     worlds-cannot-activate:
# #       - hub
# #   limitedplayer:
# #     max-active-portals: 10
# #     worlds-can-activate:
# #       - world
groups: {}

# if you have a metadata option enabled and you
# disable it, any collected data will be lost.
metadata:
  # If you wish to use 'max-active-portals' on
  # your server, you must set this to true
  track-active-portal-counts: false

  # If any metadata are enabled, a metadata file will
  # be kept in the plugin's folder. Otherwise, no file
  # will be created and you can ignore this section.
  #   Minimum interval of 60 is allowed.
  autosave:
    enabled: true
    interval: 1200  # seconds

# Customize the plugin's teleportal multi-block structure.
# 'cross-world' allows players to link teleportals between different worlds.
teleportal:
  cross-world: true

# Customize the plugin's gateway prism item.
# 'reusable' means the gateway prism is dropped when the portal is broken.
# You may use 'recipe-shapeless' instead of 'recipe-shaped'.
#   Requires a full PLUGIN reload for changes to take effect.
#   Does not affect existing items in the world.
#   Existing items will still work.
gateway-prism:
  reusable: true
  amount: 1
  material: GOLDEN_SWORD
  display: "&bGateway Prism"
  lore:
    - "&7Shift + right click to LINK."
    - "&7Right click to ACTIVATE."
  # recipe-shapeless:
  #   - ENDER_EYE
  #   - DRAGON_HEAD
  #   - ENDER_EYE
  #   - SHULKER_SHELL
  #   - END_CRYSTAL
  #   - SHULKER_SHELL
  #   - GOLD_INGOT
  #   - BEACON
  #   - GOLD_INGOT
  recipe-shaped:
    shape:
      - "OwO"
      - "*u*"
      - "-v-"
    map:
      'O': ENDER_EYE
      '*': SHULKER_SHELL
      '-': GOLD_INGOT
      'w': DRAGON_HEAD
      'u': END_CRYSTAL
      'v': BEACON
