main: me.cynadyde.teleportals.TeleportalsPlugin
name: Teleportals
version: "1.14.4-0"
api-version: "1.14"
description: >
  Build End Gateway portals in survival mode.
authors:
  - Cynadyde (May 2019)
website: N/A
commands:
  teleportals:
    description: The Teleportals Plugin command.
permissions:
  teleportals.*:
    default: false
    children:
      teleportals.admin.*: true
      teleportals.player.*: true
  teleportals.admin.*:
    default: op
    children:
      teleportals.admin.reload: true
  teleportals.player.*:
    default: true
    children:
      teleportals.player.craft: true
      teleportals.player.activate: true
      teleportals.player.use: true
  teleportals.admin.reload:
    default: false
  teleportals.player.craft:
    default: false
  teleportals.player.activate:
    default: false
  teleportals.player.use:
    default: false
