main: me.cynadyde.teleportals.TeleportalsPlugin
name: Teleportals
version: "1.14.4-1"
api-version: "1.14"
description: >
  Build End Gateway portals in survival mode.
authors:
  - Cynadyde (May 2019)
website: N/A
commands:
  teleportals:
    description: The Teleportals plugin command.
permissions:
  teleportals.*:
    description: "Grants all abilities."
    default: false
    children:
      teleportals.admin.*: true
      teleportals.player.*: true
  teleportals.admin.*:
    description: "Grants all admin abilities."
    default: op
    children:
      teleportals.admin.spawn: true
      teleportals.admin.reload: true
  teleportals.player.*:
    description: "Grants all player abilities."
    default: true
    children:
      teleportals.player.craft: true
      teleportals.player.link: true
      teleportals.player.activate: true
      teleportals.player.use: true
  teleportals.admin.spawn:
    description: "Grants ability to spawn in a gateway prism."
    default: false
  teleportals.admin.reload:
    description: "Grants ability to reload the config file."
    default: false
  teleportals.player.craft:
    description: "Grants ability to craft a gateway prism."
    default: false
  teleportals.player.link:
    description: "Grants ability to link up a gateway prism."
    default: false
  teleportals.player.activate:
    description: "Grants ability to activate a teleportal."
    default: false
  teleportals.player.use:
    description: "Grants ability to use a teleportal."
    default: false
